spring:
  profiles:
    active: dev
  application:
    name: persistence
  flyway:
    enabled: true
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
  r2dbc:
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
server:
  port: 8081
  http2:
    enabled: true
  ssl:
    enabled: false
  compression:
    enabled: true
    mime-types: text/html,text/plain,text/css,application/javascript,application/json
grpc:
  server:
    port: 9090
management:
  endpoints:
    web:
      exposure:
        include: "*"
application:
  cors:
   allowed.origins: "*"
   allowed.methods: "*"
  kafka:
    bootstrapAddress: localhost:9092
    groupId: persistenceApp
    topic: auditing
    stream:
      topic: reverseAuditing
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:mem:messaging;DB_CLOSE_DELAY=-1
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  r2dbc:
    url: r2dbc:h2:mem:///messaging;DB_CLOSE_DELAY=-1
  h2:
    console:
      enabled: true
  flyway:
    locations: classpath:db/migration/h2,classpath:/db/testdata/h2
logging:
  level:
    root: INFO
    ch.valtech: DEBUG
management:
  security:
    username: actuator
    password: actuator
application:
  token.url: http://localhost:8180/auth/realms/cluster/protocol/openid-connect/token
---
spring:
  config:
    activate:
      on-profile: prod
    import: file:/etc/config/application-prod.yml
  datasource:
    url: jdbc:mariadb://localhost:3306/messaging
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
  r2dbc:
    url: r2dbc:mariadb://localhost:3306/messaging
    pool:
      max-life-time: 8m
    properties:
      sslMode: ENABLE_WITHOUT_HOSTNAME_VERIFICATION
  flyway:
    locations: classpath:db/migration/mariadb
server:
  servlet:
    context-path: /persistence